default_install_hook_types:
- pre-commit
- commit-msg
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.0.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
    args: [feat, fix, doc, chore, test, build, merge, refactor]
- repo: https://github.com/domluna/JuliaFormatter.jl
  rev: v2.1.6
  hooks:
  - id: julia-formatter
- repo: local
  hooks:
  - id: format nix
    name: Format Nix Code
    language: system
    entry: nix fmt
    files: .*\.nix$
