name = "Manifest2Nix"
uuid = "55c00322-6feb-41de-aa1f-e2512edad3af"
authors = ["Leni Aniva <a@leni.sh>"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
JuliaFormatter = "2.1.6"
Pkg = "1.11.0"
TOML = "1.0.3"

[extras]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
