name = "simple"
uuid = "4ef67b23-529d-46c7-aad8-271324168c9c"
authors = ["Leni Aniva <a@leni.sh>"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"

[compat]
ArgParse = "1.2.0"
