# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.0"
manifest_format = "2.0"
project_hash = "1efa96b0832af8550eaa287362678fe06bcbc5d6"

[[deps.Minimal]]
path = "."
uuid = "50844a0e-b00b-440b-a496-1fd27e480955"
version = "0.1.0"
